### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cartman4** [joshua-m-david/jerichoencryption#4]
Hey nice work.
I thought about this project and had a idea but i dont know if it is a needed one or good one. 

I think it would be more user friendly if we need to meet only once to give the other users their one-time-pads. So my idea to solve this was, we create a seperate one-time-pad for the creator of the chat which is used to send new generated one time pads to the users. This needs to be regenerate everytime it is used obviously to prevent reusing.

**Comment by joshua-m-david** [comment]
Thank you, it is still a work in progress but it will get there eventually.

> I think it would be more user friendly if we need to meet only once to give the other users their one-time-pads. So my idea to solve this was, we create a seperate one-time-pad for the creator of the chat which is used to send new generated one time pads to the users. This needs to be regenerate everytime it is used obviously to prevent reusing.

I agree it is more user friendly to only meet once. I think what you are meaning is to initially create a very big pad (many megabytes) which is also given to the user/s in the initial physical key exchange, but it is not used immediately and it is reserved for later use in case the creator of the chat wants to start afresh and use new pads? The chat creator cannot create and send out new pads over the existing one-time pad encrypted channel as that would burn through existing key material, defeating the purpose. Also you cannot encrypt it any other way and send the new keys over the internet (e.g. a cascade of three 256 bit stream ciphers) as that would no longer be information-theoretically secure. Physical key exchange is the best method.

To that end there already exist some methods to exchange all the one-time pads you need up front in a single meeting and have some backup/reserve pads if something goes wrong or you run out:

1. Create the pads from two photos. Export the one-time pads as text files. Name them `one-time-pads-original-alice.txt` and `one-time-pads-original-bob.txt`. Those are the first set of pads to be used for communicating. Delete the two photos and restart the TRNG. Create more pads from two fresh new photos. Export the one-time pads as text files. Name them `one-time-pads-backup-1-alice.txt` and `one-time-pads-backup-1-bob.txt`. Once you've exchanged the pads with the other user, tell them to store the backup pads in a safe (or other secure location) and they can be retrieved for later. Each set of two photos might provider enough one-time pads for between 2000-4000 messages. So you can have 10+ sets of backup pads if you wish and they all get exchanged to the other user/s in the initial key exchange. When you export the pad text files you can also put a different encryption password on each one so they can only be unencrypted and loaded into the program by the chat creator when they want them to be unlocked. This is a good idea to do so all the pads cannot be compromised at once. This password can be sent over the pre-existing OTP channel. E.g. "Hey we are getting low on messages, switch to backup set #1, the password is: XP788sdjRfJsSk33z28dfrQ." Then the other users just load up the new pad set.

2. With the original OTP exchange, have some spare photographs from your digital camera on the storage MicroSD/SD/USB/CD/DVD you are exchanging. E.g. name them `IMG_3243_backup-1a.png`, `IMG_3244_backup-1b.png`, `IMG_3257_backup-2a.png`, `IMG_3258_backup-2b.png`. So when you want to start using new pads, the other user/s loads up the backup-1a and backup-1b images and creates the one-time pads. If each user follows the same process with the same inputs they should end up with all the same pads. Then it is just a matter of deciding which user loads which pads. So the order of the names is important on the export dialog. Each user can load their pads and delete the others and the images. This process is more difficult and less user friendly so you may prefer option one. However it could be useful for longer term chat continuation and it would help if later versions of the program are incompatible with loading the older one-time-pad text file formats any longer.

I hope that makes sense.

**Comment by deltaghost101** [comment]
Can we use an external HWRNG like chaoskey or OneRNG with Jericho Comms. ?

**Comment by joshua-m-david** [comment]
> Can we use an external HWRNG like chaoskey or OneRNG with Jericho Comms. ?

Yes definitely. That is a very important feature of the software so that users can use their own trusted HWRNG if they wish. There's a section about it mentioned in [the whitepaper](https://joshua-m-david.github.io/jerichoencryption/information.html#trng-custom).

After a brief search, I could not find any instructions or notes about how you get the random data out of the chaoskey but if you can extract some output from the HWRNG somehow and save it as a binary file then you can load that data into the Jericho Comms program very easily. Then the program runs some quick randomness tests over the data and then the data is split up into individual one-time pads for messages. I read that OneRNG hooks into /dev/random and feeds it with random data from the HWRNG so I have documented some steps here:

1. Install the OneRNG software, pre-requisites and test it.

2. Extract some data from /dev/random to a file (**NB:** not /dev/urandom because we want information-theoretic randomness and to remove those bytes from the randomness pool so they cannot be used again). The following command gets 1 MB from /dev/random which is enough for about 5460 messages (if you need more, make separate sets otherwise the browser may run into localStorage size limitations):

`dd if=/dev/random of=randomdata.bin bs=1M count=1`

3. Load the Jericho Comms client software. Then click the 'Create one-time pads' button, then the 'Load custom random data' button.

4. At this screen browse for the 'randomdata.bin' file you just created and the program will load the random data.

5. Once the tests have run you can click the 'Export' button in the top right to split up the random data into separate one-time pads, then distribute the files to each chat user.

**Comment by deltaghost101** [comment]
Thank you , Joshua .

--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com

13. Jun 2017 09:21 by notifications@github.com:

**Comment by deltaghost101** [comment]
Do you have a bitmessage account where we can contact you ?

**Comment by joshua-m-david** [comment]
@deltaghost101 Sure it is:

`BM-2cTFj51AZNCf1k1gB24o9YFGTHuca8UNQN`
