### ISSUE TITLE
you can't even acceess your new key

### ISSUE THREAD

**Issue by teruteru128** [joshua-m-david/jerichoencryption#5]
Hi, your key (0xDC768471C467B6D0) has expired and you can't even access your new key (because sks keyservers is no longer in operation).
Would you please upload the updated key to https://keys.openpgp.org/ ?

**Comment by joshua-m-david** [comment]
Hi,

Many thanks for notifying me. I thought it might have still been available on https://keybase.io/joshua_m_david but it got removed from there as well (probably because it was expired). I'll fix that soon.

Anyway, I have fixed the expiry and uploaded it to:

1) https://keys.openpgp.org/search?q=CF3F79EE011459BA0A599E9CDC768471C467B6D0

2) https://keyserver.ubuntu.com/pks/lookup?search=0xdc768471c467b6d0&fingerprint=on&hash=on&op=get

Also I have attached it here:
[joshua-m-david-public-key-2022-04.txt](https://github.com/joshua-m-david/jerichoencryption/files/8544682/joshua-m-david-public-key-2022-04.txt)

Fingerprint as usual is still:
![Screenshot from 2022-04-22 19-40-43](https://user-images.githubusercontent.com/5305430/164813949-6a48f548-fd83-47f2-a9b8-ee031f24e5ac.png)

I will do a release sometime this year and update the rest of the documentation at the same time to tell users to download from the new keyserver.
